RegisterNetEvent(("%s:buyMask"):format(KaizoMasques.Utils.PrefixEvent))
AddEventHandler(("%s:buyMask"):format(KaizoMasques.Utils.PrefixEvent), function()
    KaizoMasques.Utils.InSide("skinchanger:change", "mask_1", _Client.MainMenu.MaskIndex, -1)
    KaizoMasques.Utils.InSide("skinchanger:change", "mask_2", _Client.MainMenu.MaskColorIndex)
    KaizoMasques.Utils.InSide('skinchanger:getSkin', function(skin)
        KaizoMasques.Utils.ServerSide('esx_skin:save', skin)
    end)
end)

RegisterNetEvent(("%s:notMoney"):format(KaizoMasques.Utils.PrefixEvent))
AddEventHandler(("%s:notMoney"):format(KaizoMasques.Utils.PrefixEvent), function()
    ESX.TriggerServerCallback('esx_skin:getPlayerSkin', function(skin)
        KaizoMasques.Utils.InSide('skinchanger:loadSkin', skin)
    end)
end)

RegisterNetEvent(("%s:showNotification"):format(KaizoMasques.Utils.PrefixEvent))
AddEventHandler(("%s:showNotification"):format(KaizoMasques.Utils.PrefixEvent), function(msg)
    KaizoMasques.Utils.ShowNotification(msg)
end)