---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by iTexZ.
--- DateTime: 05/11/2020 02:17
---

local TextPanels = {
    Background = { Dictionary = "OnestlaFilsDePuteGrr", Texture = "gradient_bgd", Y = 38, Width = 431, Height = 42 },
}

---@type Panel
function KaizoUI.RenderSprite2(Dictionary, Texture)
    local CurrentMenu = KaizoUI.CurrentMenu
    if CurrentMenu ~= nil then
        if CurrentMenu() then
            RenderSprite(Dictionary, Texture, CurrentMenu.X, CurrentMenu.Y + TextPanels.Background.Y + CurrentMenu.SubtitleHeight + KaizoUI.ItemOffset + (KaizoUI.StatisticPanelCount * 42), TextPanels.Background.Width + CurrentMenu.WidthOffset, TextPanels.Background.Height + 200, 0, 255, 255, 255, 255);
            KaizoUI.StatisticPanelCount = KaizoUI.StatisticPanelCount + 1
        end
    end
end

function KaizoUI.RenderSprite(Dictionary,Texture)
    local CurrentMenu = KaizoUI.CurrentMenu
    if CurrentMenu ~= nil then
        if CurrentMenu() then

            RenderSprite(Dictionary, Texture, CurrentMenu.X, CurrentMenu.Y + CurrentMenu.SubtitleHeight + KaizoUI.ItemOffset, 431 + (CurrentMenu.WidthOffset / 1), 228)
            

            KaizoUI.ItemOffset = KaizoUI.ItemOffset + 228
        end
    end
end

local TextPanelVehicle = {
    Background = { Dictionary = "OnestlaFilsDePuteGrr", Texture = "gradient_bgd", Y = 0.25, Width = 431, Height = 42 },
}

---@type Panel
function KaizoUI.RenderWeapon(Dictionary, Texture)
    local CurrentMenu = KaizoUI.CurrentMenu
    if CurrentMenu ~= nil then
        if CurrentMenu() then
            RenderSprite(Dictionary, Texture, CurrentMenu.X, 560.25, TextPanelVehicle.Background.Width + CurrentMenu.WidthOffset, TextPanelVehicle.Background.Height + 200, 0, 255, 255, 255, 255);
            KaizoUI.StatisticPanelCount = KaizoUI.StatisticPanelCount + 1
        end
    end
end

---@type Panel
function KaizoUI.RenderVehicle(Dictionary, Texture)
    local CurrentMenu = KaizoUI.CurrentMenu
    if CurrentMenu ~= nil then
        if CurrentMenu() then
            RenderSprite(Dictionary, Texture, CurrentMenu.X, 560.25, TextPanelVehicle.Background.Width + CurrentMenu.WidthOffset, TextPanelVehicle.Background.Height + 200, 0, 255, 255, 255, 255);
            KaizoUI.StatisticPanelCount = KaizoUI.StatisticPanelCount + 1
        end
    end
end

---@type Panel
function KaizoUI.RenderCaisse(Dictionary, Texture)
    local CurrentMenu = KaizoUI.CurrentMenu
    if CurrentMenu ~= nil then
        if CurrentMenu() then
            RenderSprite(Dictionary, Texture, CurrentMenu.X, 258, TextPanelVehicle.Background.Width + CurrentMenu.WidthOffset, TextPanelVehicle.Background.Height + 200, 0, 255, 255, 255, 255);
            KaizoUI.StatisticPanelCount = KaizoUI.StatisticPanelCount + 1
        end
    end
end

---@type Panel
function KaizoUI.RenderPackEntreprise(Dictionary, Texture)
    local CurrentMenu = KaizoUI.CurrentMenu
    if CurrentMenu ~= nil then
        if CurrentMenu() then
            RenderSprite(Dictionary, Texture, CurrentMenu.X, 345, TextPanelVehicle.Background.Width + CurrentMenu.WidthOffset, TextPanelVehicle.Background.Height + 200, 0, 255, 255, 255, 255);
            KaizoUI.StatisticPanelCount = KaizoUI.StatisticPanelCount + 1
        end
    end
end

function KaizoUI.RenderPackIllegal(Dictionary, Texture)
    local CurrentMenu = KaizoUI.CurrentMenu
    if CurrentMenu ~= nil then
        if CurrentMenu() then
            RenderSprite(Dictionary, Texture, CurrentMenu.X, 285, TextPanelVehicle.Background.Width + CurrentMenu.WidthOffset, TextPanelVehicle.Background.Height + 200, 0, 255, 255, 255, 255);
            KaizoUI.StatisticPanelCount = KaizoUI.StatisticPanelCount + 1
        end
    end
end